### ISSUE TITLE
Working array missing from lab?

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/ruby-vs-js-arrays-study#2]
Probably whatever gets is used here ga-wdi-boston/ruby-arrays#4

**Comment by neugierige** [comment]
updated: https://github.com/ga-wdi-boston/ruby-vs-js-arrays-study/blob/015/master/bin/study.js

**Comment by gaand** [comment]
Closed by 61c71534f1fbe2b86e1d8608e206c80a2655f321
